# Generated by Django 4.2.6 on 2023-10-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallermecanico', '0002_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
