# Generated by Django 4.2.6 on 2023-10-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallermecanico', '0003_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone', models.CharField(max_length=20)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('visitor_message', models.TextField()),
            ],
        ),
    ]
